title: QA Test Manager
description: Manual test case management and GitHub integration platform
baseurl: "/qa-demo-1"
url: "https://synjan.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Navigation
header_pages:
  - getting-started.md
  - user-guide.md
  - api-reference.md
  - deployment.md

# GitHub Pages supported plugins only
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - README.md

# Social media and contact
github_username: synjan
author:
  name: QA Test Manager Team